- hosts: all
  tasks:
  - name: Ansible create multiple files with_items
    file:
      path: {{ item }}
      dest: /tmp
      mode: 0774
    with_items:
       - hello1
       - hello2
       - hello3
       - sub_folder/hello4
