- hosts: all
  tasks:
  - name: Copy multiple files in Ansible with different permissions
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{item.mode}}"
    with_items:
      - { src: './test1', dest: '/tmp/devops_system1', mode: '0777'}
      - { src: './test2', dest: '/tmp/devops_system2', mode: '0707'}
      - { src: './test3', dest: '/tmp2/devops_system3', mode: '0575'}

---
- hosts: "localhost"
  connection: "local"
  vars:
    users:
    - "paul"
    - "tanya"
    - "ruby"
  tasks:
  - name: "create groups"
    group:
      name: "{{ item }}"
      state: present
    with_items:
          - admin
          - www-data
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
      groups: "admin,www-data"
    with_items: "{{ users }}"

  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"

  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers" # path: in version 2.3
      state: "present"
      regexp: "^%admin"
      line: "%admin ALL=(ALL) NOPASSWD: ALL"
