---
- hosts: centos 
  become: yes
  tasks:
    - name: install a webserver redhat/centos
      yum:
        name: httpd
        state: latest
      tags: install
    - name: start the service
      service:
         name: httpd
         state: started
      tags: install

    - name: stop the service
      service:
         name: httpd
         state: stopped
      tags: uninstall
    - name: uninstall a webserver on centos 
      yum:
        name: httpd
        state: absent
      tags: uninstall
