---
- hosts: ubuntu 
  become: yes
  tasks:
    - name: install a webserver ubuntu
      apt:
        name: apache2
        state: latest
      tags: install
    - name: start the service
      service:
         name: apache2
         state: started
      tags: install

    - name: stop the service
      service:
         name: apache2
         state: stopped
      tags: uninstall
    - name: uninstall a webserver on ubuntu
      apt:
        name: apache2
        state: absent
      tags: uninstall
