---
- hosts: ubuntu 
  become: yes
  tasks:
   - name: Add Docker GPG key ubuntu
     apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
     tags: ubuntu

   - name: Install basic list of packages ubuntu
     apt:
        name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
        state: present
        update_cache: yes
     tags: ubuntu

   - name: Add Docker APT repository ubuntu
     apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
     tags: ubuntu

   - name: Install Docker packages ubuntu
     apt:
        name: ['docker-ce=5:18.09.9~3-0~ubuntu-bionic','docker-ce-cli=5:18.09.9~3-0~ubuntu-bionic', 'containerd.io=1.2.6-3']
        state: present
     tags: ubuntu

   - name: Start Docker service
     service:
       name: docker
       state: started
       enabled: yes
     tags: 
       - ubuntu
