---
- hosts: all
  become: yes
  tasks:
   - name: Add Docker GPG key ubuntu
     apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
     tags: ubuntu

   - name: Install basic list of packages ubuntu
     apt:
        name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
        state: present
        update_cache: yes
     tags: ubuntu

   - name: Add Docker APT repository ubuntu
     apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
     tags: ubuntu

   - name: Install Docker packages ubuntu
     apt:
        name: ['docker-ce=5:18.09.9~3-0~ubuntu-bionic','docker-ce-cli=5:18.09.9~3-0~ubuntu-bionic', 'containerd.io=1.2.6-3']
        state: present
     tags: ubuntu

   - name: Remove docker if installed from CentOS repo
     yum:
       name: "{{ item }}"
       state: absent 
     with_items:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
     tags: centos
   - name: Install basic packages for CentOS
     yum:
        name: [ 'yum-utils','device-mapper-persistent-data','lvm2' ]
        state: latest
     tags: centos

   - name: Add Docker repo CentOS 
     get_url:
       url: https://download.docker.com/linux/centos/docker-ce.repo
       dest: /etc/yum.repos.d/docer-ce.repo
     tags: centos

   - name: Install Docker CentOS
     package:
       name: [ 'docker-ce','docker-ce-cli','containerd.io']
       state: latest
     tags: centos

   - name: Start Docker service
     service:
       name: docker
       state: started
       enabled: yes
     tags: 
       - centos
       - ubuntu
