- hosts: web
  become: yes
  tasks:
  - import_tasks: install-docker-ubuntu.yml
    when: ansible_distribution == 'Ubuntu'

  - import_tasks: install-docker-centos.yml
    when: ansible_distribution == 'CentOS'
