---
- hosts: ubuntu
  tasks: 
    - name: Add the Jenkins APT repository key
      apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present

    - name: Add the Jenkins APT repository
      apt_repository: repo="deb http://pkg.jenkins-ci.org/debian binary/" state=present

    - name: Install Jenkins
      apt: name=jenkins state=latest
