---
- hosts: all
  tasks:
    - command: echo {{ item }}
      loop: [ 0, 2, 4, 6, 8, 10 ]
      when: item > 5

- name: check registered variable for emptiness
  hosts: all
  tasks:
      - name: list contents of directory
        command: ls mydir
        register: contents

      - name: check contents for emptiness
        debug:
          msg: "Directory is empty"
        when: contents.stdout == ""

- hosts: all
  become: yes
  tasks:
    - shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      when: "foo is defined"

- hosts: web
  become: yes
  tasks:
    - name: "Determine if the HTTPD is installed"
      register: validatehttpd
      shell: httpd
    - name: Ensure Apache is at the Latest version
      yum:
        name: httpd
        state: latest
      when: "'not found' in validatehttpd.stdout"

- hosts: all
  tasks:
    - name: Restart Apache on webservers
      become: yes
      service:
        name: apache2
        state: restarted
      when: web in group_names

- hosts: all
  vars:
     os: "redhat"
  tasks:
    - name: "shut down CentOS 6 systems"
      command: /sbin/shutdown -t now
      when:
        - os == "CentOS"
