# For checking if a particular object is a directory and also it exists we can combine the ‘exists’ and ‘isdir’ return values. The ‘isdir’ value will be true if the object is a directory and else false.

- hosts: all
  tasks:
  - name: Ansible check file exists example.
    stat:
      path: /home/ansiblebot/prompt.yaml
    register: file_details

  - debug:
      msg: "The file or directory exists"
    when: file_details.stat.exists
---

# below we storing the details of the stat module execution in a register named ‘file_details’. The module returns a lot of return values, and one of them is ‘exists’.  It will return a boolean value, true or false, depending on the status of the file.

# We can use the ‘isreg‘ return value for checking if its a return value. It will be true if the path is a regular file.

- hosts: all
  tasks:
  - name: Ansible check file exists example.
    stat:
      path: /home/ansiblebot/prompt.yaml
    register: file_details

  - debug:
      msg: "The file or directory exists"
    when: file_details.stat.exists

  - debug:
      msg: "Ansible file exists example"
    when: file_details.stat.exists and file_details.stat.isreg

 - debug:
      msg: "It is a file"
    when: file_details.stat.exists and file_details.stat.isdir == false and file_details.stat.islnk == false
