- name: Add Docker GPG key ubuntu
  apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg

- name: Install basic list of packages ubuntu
  apt:
     name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
     state: present
     update_cache: yes

- name: Add Docker APT repository ubuntu
  apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker packages ubuntu
  apt:
     name: ['docker-ce=5:18.09.9~3-0~ubuntu-bionic','docker-ce-cli=5:18.09.9~3-0~ubuntu-bionic', 'containerd.io=1.2.6-3']
     state: present

- name: configure docker properties 
  copy: 
    src: daemon.json
    dest: /var/lib/docker
  notify: "restart docker"

- name: Start Docker service
  service:
    name: docker
    enabled: yes

- file: 
   path: /tmp/nar.txt
   state: touch
  register: a

- debug: 
    msg: "invoking handler"
  when: a.changed
  notify: "restart docker"
