- hosts: all
  tasks:
  - name: Copy multiple files in Ansible with different permissions
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{item.mode}}"
    with_items:
      - { src: './test1', dest: '/tmp/devops_system1', mode: '0777'}
      - { src: './test2', dest: '/tmp/devops_system2', mode: '0707'}
      - { src: './test3', dest: '/tmp2/devops_system3', mode: '0575'}
