- hosts: all
  become: true
  tasks:
   - name: Create fact directory
     file:
       path: /etc/ansible/facts.d/
       state: directory

   - name: Create a static custom fact mydata
     copy:
       content: '"hello"'
       dest: /etc/ansible/facts.d/mydata.fact

   - name: Create a dynamic custom fact foobar
     copy:
       dest: /etc/ansible/facts.d/docker.fact
       mode: 0775
       content: |
         #!/usr/bin/python3
         import json
         def render_data(data):
            return json.dumps(data)
         arbitrary_data = {}
         arbitrary_data["foobar"] = []
         arbitrary_data["foobar"].append("foo")
         if True:
            arbitrary_data["foobar"].append("bar")
         print(render_data(arbitrary_data["foobar"]))
